### PR TITLE
Fix import error

### PR DESCRIPTION
**Pull request by sayanarijit**
Error:

```
>>> import dnsmadeeasy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'dnsmadeeasy'
```

Fix:

Use a simpler structure and simpler version of setup.py.

### CODE REVIEW

**Comment by sayanarijit** [comment]
Still untested. Will test and confirm.

**Comment by moses-palmer** [comment]
Thank you for your contribution!

With that said, I do not really get what this fixes. When do you get an import error? *libcloud-dnsmadeeasy* can be installed from _PyPi_, or from a cloned repository using `python setup.py install`.

**Comment by sayanarijit** [comment]
For some reason poetry fails to install it from git.

```
(.venv) ➜  /tmp poetry add git+https://github.com/moses-palmer/libcloud-dnsmadeeasy

Updating dependencies
Resolving dependencies... (47.1s)

Writing lock file


Package operations: 10 installs, 0 updates, 0 removals

  - Installing certifi (2019.11.28)
  - Installing chardet (3.0.4)
  - Installing idna (2.9)
  - Installing urllib3 (1.25.8)
  - Installing enum34 (1.1.10)
  - Installing requests (2.23.0)
  - Installing typing (3.7.4.1)
  - Installing apache-libcloud (2.8.1)
  - Installing hammock (0.2.4)
  - Installing libcloud-dnsmadeeasy (1.0 4c58302)
(.venv) ➜  /tmp python

WARNING: Python 2.7 is not recommended.
This version is included in macOS for compatibility with legacy software.
Future versions of macOS will not include Python 2.7.
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.16 (default, Dec 13 2019, 18:00:32)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.32.4) (-macos10.15-objc-s on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import libcloud.dns.providers
>>> import dnsmadeeasy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named dnsmadeeasy
>>>
```
Could also be a poetry related issue. Will check.

**Comment by sayanarijit** [comment]
```
(.venv) ➜ ~/.poetry/bin/poetry add libcloud-dnsmadeeasy
Using version ^1.0 for libcloud-dnsmadeeasy

Updating dependencies
Resolving dependencies... (3.5s)

Writing lock file

No dependencies to install or update

(.venv) ➜  python
Python 3.7.5 (default, Feb  8 2020, 11:45:41)
[Clang 7.1.0 (tags/RELEASE_710/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import libcloud.dns.providers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'libcloud'
>>>
(.venv) ➜  deactivate
➜  ~/.poetry/bin/poetry install
Installing dependencies from lock file


Package operations: 0 installs, 1 update, 0 removals

  - Updating libcloud-dnsmadeeasy (1.1 0e9aa08 -> 1.0)
  - Installing ebn (0.1.0)
➜ python
Python 3.7.5 (default, Feb  8 2020, 11:45:41)
[Clang 7.1.0 (tags/RELEASE_710/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import libcloud.dns.providers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'libcloud'
>>>
```

Not easy to debug... 😅

**Comment by moses-palmer** [comment]
For the moment, I will assume that this is a *poetry* related bug, possibly caused by unexpected meta data for this package.

I have installed poetry in a *virtualenv* and then added this library using the command you provided. *poetry* appears to create an _.egg-link_ file pointing to _.../src/libcloud-dnsmadeeasy/build_ inside the *virtualenv* directory, but it does not appear to actually have populated the build directory; all _libcloud-dnsmadeeasy_ files are located under _.../src/libcloud-dnsmadeeasy/lib/_.

**Comment by sayanarijit** [comment]
@moses-palmer if possible, can you please publish the v1.1 on PyPi?

**Comment by moses-palmer** [comment]
@sayanarijit, I am unfortunately uncomfortable with merging this rather large change without a thorough review, and I don't really have time for that right now.

Perhaps you can provide me with motivation. Why do you need to use `poetry add git+https://github.com/moses-palmer/libcloud-dnsmadeeasy` instead of `poetry add libcloud-dnsmadeeasy`? The former insists on installing the package in development mode, whereas the latter downloads from _PyPi_ and actually works.

**Comment by sayanarijit** [comment]
@moses-palmer I mean publishing from your master branch which has v1.1
The version on pypi shows outdated v1.0. this is why I needed to do poetry add git+https://...

**Comment by sayanarijit** [comment]
We have been using the master branch version via pipenv. However, now we are migrating to poetry. I don't want to break anything by changing the version from v1.1 to v1.0. Although I don't have much idea if it will break anything at all.

**Comment by moses-palmer** [comment]
Ah, sorry; I did not realise that it was not published.

This has been fixed, and *libcloud-dnsmadeeasy* is now [available](https://pypi.org/project/libcloud-dnsmadeeasy/1.1/).

**Comment by sayanarijit** [comment]
Great... Thanks a lot. 🙂
Closing this PR.

**Pull request closed without merging**
