### PR TITLE
fixed import error

### PR DESCRIPTION
**Pull request by estol**
with python 3 the original import statements caused import errors. works fine this way for me.

### CODE REVIEW

**Comment by moses-palmer** [comment]
Thank you for the PR!

I am currently travelling, but I will merge this when I return. I made a
comment on part of the commit.


On 14 Nov 2017 10:24 pm, "estol" <notifications@github.com> wrote:

with python 3 the original import statements caused import errors. works
fine this way for me.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/moses-palmer/libcloud-dnsmadeeasy/pull/2
Commit Summary

   - fixed import error

File Changes

   - *M* lib/dnsmadeeasy/__init__.py
   <https://github.com/moses-palmer/libcloud-dnsmadeeasy/pull/2/files#diff-0>
   (4)

Patch Links:

   - https://github.com/moses-palmer/libcloud-dnsmadeeasy/pull/2.patch
   - https://github.com/moses-palmer/libcloud-dnsmadeeasy/pull/2.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/moses-palmer/libcloud-dnsmadeeasy/pull/2>, or mute the
thread

**Comment by estol** [comment]
@moses-palmer no reason at all, when I faced the import issue, I monkey patched my version of the file like this and worked. Never tried it with `from . import driver`

**Comment by estol** [comment]
@moses-palmer any updates on this?

**Comment by moses-palmer** [comment]
Sorry about the delay---I complete forgot about this!

**Pull request merged**
